### ISSUE TITLE
WP Redis Error

### ISSUE THREAD

**Issue by dbarczak1** [pantheon-systems/wp-redis#334]
Good morning,
I just received an email from my wordpress site that is on Pantheon that WP Redis has caused an error on my live site. I had just updated it to the version released 6 days ago. research.udel.edu

I wanted to let you know if this may help. 

db

Error Details
=============
An error of type E_ERROR was caused in line 1275 of the file /code/wp-content/plugins/wp-redis/object-cache.php. Error message: Uncaught RedisException: read error on connection to 10.128.1.13:19303 in /code/wp-content/plugins/wp-redis/object-cache.php:1275
Stack trace:
#0 /code/wp-content/plugins/wp-redis/object-cache.php(1275): Redis->get('transient:frm_o...')
#1 /code/wp-content/plugins/wp-redis/object-cache.php(655): WP_Object_Cache->_call_redis('get', 'transient:frm_o...')
#2 /code/wp-content/plugins/wp-redis/object-cache.php(137): WP_Object_Cache->get('frm_options', 'transient', false, NULL)
#3 /code/wp-includes/option.php(838): wp_cache_get('frm_options', 'transient')
#4 /code/wp-content/plugins/formidable/classes/models/FrmSettings.php(46): get_transient('frm_options')
#5 /code/wp-content/plugins/formidable/classes/helpers/FrmAppHelper.php(135): FrmSettings->__construct(Array)
#6 /code/wp-content/plugins/formidable/classes/controllers/FrmStylesController.php(92): FrmAppHelper::get_settings()
#7 /code/wp-content/plugins/formidable/classes/controllers/FrmFormsController.php(2137): FrmStylesController::enqueue_css('register')
#8

**Comment by deltafactory** [comment]
I know this is an extremely stale issue report but I am experiencing the same thing _on a Pantheon-hosted site_ and it triggers the WP Critical Error page/email even if it only occurs for a second. Could this be handled more gracefully?
